<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "location_view".
 *
 * @property integer $id
 * @property string $latitude
 * @property string $longitude
 * @property string $loc_name
 * @property string $loc_name_la
 * @property string $type_location_id
 * @property integer $provinces_id
 * @property integer $districts_id
 * @property string $villages_id
 * @property string $aliasModel
 */
abstract class LocationView extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'location_view';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id', 'provinces_id', 'districts_id'], 'integer'],
            [['latitude', 'longitude', 'type_location_id', 'villages_id'], 'string', 'max' => 45],
            [['loc_name', 'loc_name_la'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'latitude' => 'Latitude',
            'longitude' => 'Longitude',
            'loc_name' => 'Loc Name',
            'loc_name_la' => 'Loc Name La',
            'type_location_id' => 'Type Location ID',
            'provinces_id' => 'Provinces ID',
            'districts_id' => 'Districts ID',
            'villages_id' => 'Villages ID',
        ];
    }




}
