<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "location_view_details".
 *
 * @property integer $phone
 * @property integer $email
 * @property string $details
 * @property string $details_la
 * @property integer $location_id
 * @property string $aliasModel
 */
abstract class LocationViewDetails extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'location_view_details';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['phone', 'email', 'location_id'], 'integer'],
            [['details', 'details_la'], 'string']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'phone' => 'Phone',
            'email' => 'Email',
            'details' => 'Details',
            'details_la' => 'Details La',
            'location_id' => 'Location ID',
        ];
    }




}
