<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "location_tem".
 *
 * @property integer $id
 * @property string $latitude
 * @property string $longitude
 * @property string $name
 * @property string $name_la
 * @property string $details
 * @property string $details_la
 * @property string $province_code
 * @property string $district_code
 * @property string $village
 * @property string $type_id
 * @property string $vl_id
 * @property string $aliasModel
 */
abstract class LocationTem extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'location_tem';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['details', 'details_la'], 'string'],
            [['latitude', 'longitude', 'province_code', 'district_code', 'village', 'type_id', 'vl_id'], 'string', 'max' => 45],
            [['name', 'name_la'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'latitude' => 'Latitude',
            'longitude' => 'Longitude',
            'name' => 'Name',
            'name_la' => 'Name La',
            'details' => 'Details',
            'details_la' => 'Details La',
            'province_code' => 'Province Code',
            'district_code' => 'District Code',
            'village' => 'Village',
            'type_id' => 'Type ID',
            'vl_id' => 'Vl ID',
        ];
    }




}
