<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "photo".
 *
 * @property integer $id
 * @property string $photo
 * @property integer $location_details_id
 * @property integer $location_id
 *
 * @property \app\models\Location $location
 * @property string $aliasModel
 */
abstract class Photo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'photo';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['photo', 'location_details_id', 'location_id'], 'required'],
            [['photo'], 'string'],
            [['location_details_id', 'location_id'], 'integer'],
            [['location_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Location::className(), 'targetAttribute' => ['location_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'photo' => 'Photo',
            'location_details_id' => 'Location Details ID',
            'location_id' => 'Location ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocation()
    {
        return $this->hasOne(\app\models\Location::className(), ['id' => 'location_id']);
    }




}
