<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "polygon".
 *
 * @property integer $id
 * @property double $latitude
 * @property double $longitude
 * @property integer $provinces_id
 * @property integer $districts_id
 *
 * @property \app\models\Districts $districts
 * @property \app\models\Provinces $provinces
 * @property string $aliasModel
 */
abstract class Polygon extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'polygon';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['latitude', 'longitude'], 'number'],
            [['provinces_id', 'districts_id'], 'integer'],
            [['districts_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Districts::className(), 'targetAttribute' => ['districts_id' => 'id']],
            [['provinces_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Provinces::className(), 'targetAttribute' => ['provinces_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'latitude' => 'Latitude',
            'longitude' => 'Longitude',
            'provinces_id' => 'Provinces ID',
            'districts_id' => 'Districts ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistricts()
    {
        return $this->hasOne(\app\models\Districts::className(), ['id' => 'districts_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProvinces()
    {
        return $this->hasOne(\app\models\Provinces::className(), ['id' => 'provinces_id']);
    }




}
