<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "districts".
 *
 * @property integer $id
 * @property string $dis_code
 * @property string $dis_name
 * @property string $dis_name_la
 * @property double $latitude
 * @property double $longitude
 * @property integer $provinces_id
 *
 * @property \app\models\Provinces $provinces
 * @property \app\models\Location[] $locations
 * @property \app\models\Polygon[] $polygons
 * @property \app\models\Villages[] $villages
 * @property string $aliasModel
 */
abstract class Districts extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'districts';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['latitude', 'longitude', 'provinces_id'], 'required'],
            [['latitude', 'longitude'], 'number'],
            [['provinces_id'], 'integer'],
            [['dis_code'], 'string', 'max' => 45],
            [['dis_name', 'dis_name_la'], 'string', 'max' => 255],
            [['provinces_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Provinces::className(), 'targetAttribute' => ['provinces_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'dis_code' => 'Dis Code',
            'dis_name' => 'Dis Name',
            'dis_name_la' => 'Dis Name La',
            'latitude' => 'Latitude',
            'longitude' => 'Longitude',
            'provinces_id' => 'Provinces ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProvinces()
    {
        return $this->hasOne(\app\models\Provinces::className(), ['id' => 'provinces_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocations()
    {
        return $this->hasMany(\app\models\Location::className(), ['districts_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPolygons()
    {
        return $this->hasMany(\app\models\Polygon::className(), ['districts_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVillages()
    {
        return $this->hasMany(\app\models\Villages::className(), ['districts_id' => 'id']);
    }




}
