<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "location".
 *
 * @property integer $id
 * @property double $latitude
 * @property double $longitude
 * @property string $loc_name
 * @property string $loc_name_la
 * @property integer $type_location_id
 * @property integer $provinces_id
 * @property integer $districts_id
 * @property integer $villages_id
 * @property integer $user_id
 *
 * @property \app\models\Districts $districts
 * @property \app\models\Provinces $provinces
 * @property \app\models\TypeLocation $typeLocation
 * @property \app\models\User $user
 * @property \app\models\Villages $villages
 * @property \app\models\LocationDetails[] $locationDetails
 * @property \app\models\Photo[] $photos
 * @property string $aliasModel
 */
abstract class Location extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'location';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['latitude', 'longitude', 'loc_name', 'loc_name_la'], 'required'],
            [['latitude', 'longitude'], 'number'],
            [['type_location_id', 'provinces_id', 'districts_id', 'villages_id', 'user_id'], 'integer'],
            [['loc_name', 'loc_name_la'], 'string', 'max' => 255],
            [['districts_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Districts::className(), 'targetAttribute' => ['districts_id' => 'id']],
            [['provinces_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Provinces::className(), 'targetAttribute' => ['provinces_id' => 'id']],
            [['type_location_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TypeLocation::className(), 'targetAttribute' => ['type_location_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['villages_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Villages::className(), 'targetAttribute' => ['villages_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'latitude' => 'Latitude',
            'longitude' => 'Longitude',
            'loc_name' => 'Loc Name',
            'loc_name_la' => 'Loc Name La',
            'type_location_id' => 'Type Location ID',
            'provinces_id' => 'Provinces ID',
            'districts_id' => 'Districts ID',
            'villages_id' => 'Villages ID',
            'user_id' => 'User ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistricts()
    {
        return $this->hasOne(\app\models\Districts::className(), ['id' => 'districts_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProvinces()
    {
        return $this->hasOne(\app\models\Provinces::className(), ['id' => 'provinces_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTypeLocation()
    {
        return $this->hasOne(\app\models\TypeLocation::className(), ['id' => 'type_location_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVillages()
    {
        return $this->hasOne(\app\models\Villages::className(), ['id' => 'villages_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocationDetails()
    {
        return $this->hasMany(\app\models\LocationDetails::className(), ['location_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPhotos()
    {
        return $this->hasMany(\app\models\Photo::className(), ['location_id' => 'id']);
    }




}
