<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "location_busines".
 *
 * @property integer $id
 * @property string $loc_name
 * @property string $loc_name_la
 * @property double $latitute
 * @property double $logtitute
 * @property integer $type_location_id
 *
 * @property \app\models\TypeLocation $typeLocation
 * @property \app\models\LocationDetails[] $locationDetails
 * @property string $aliasModel
 */
abstract class LocationBusines extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'location_busines';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['loc_name', 'loc_name_la', 'latitute', 'logtitute', 'type_location_id'], 'required'],
            [['latitute', 'logtitute'], 'number'],
            [['type_location_id'], 'integer'],
            [['loc_name', 'loc_name_la'], 'string', 'max' => 255],
            [['type_location_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TypeLocation::className(), 'targetAttribute' => ['type_location_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'loc_name' => 'Loc Name',
            'loc_name_la' => 'Loc Name La',
            'latitute' => 'Latitute',
            'logtitute' => 'Logtitute',
            'type_location_id' => 'Type Location ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTypeLocation()
    {
        return $this->hasOne(\app\models\TypeLocation::className(), ['id' => 'type_location_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocationDetails()
    {
        return $this->hasMany(\app\models\LocationDetails::className(), ['location_id' => 'id']);
    }




}
