<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "provinces".
 *
 * @property integer $id
 * @property string $pro_code
 * @property string $pro_name
 * @property string $pro_name_la
 * @property double $latitute
 * @property double $longtitute
 *
 * @property \app\models\Districts[] $districts
 * @property \app\models\LocationDetails[] $locationDetails
 * @property \app\models\Villages[] $villages
 * @property string $aliasModel
 */
abstract class Provinces extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'provinces';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['latitute', 'longtitute'], 'required'],
            [['latitute', 'longtitute'], 'number'],
            [['pro_code'], 'string', 'max' => 45],
            [['pro_name', 'pro_name_la'], 'string', 'max' => 255],
            [['latitute'], 'unique'],
            [['longtitute'], 'unique']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pro_code' => 'Pro Code',
            'pro_name' => 'Pro Name',
            'pro_name_la' => 'Pro Name La',
            'latitute' => 'Latitute',
            'longtitute' => 'Longtitute',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistricts()
    {
        return $this->hasMany(\app\models\Districts::className(), ['provinces_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocationDetails()
    {
        return $this->hasMany(\app\models\LocationDetails::className(), ['provinces_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getVillages()
    {
        return $this->hasMany(\app\models\Villages::className(), ['provinces_id' => 'id']);
    }




}
