<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "type_location".
 *
 * @property integer $id
 * @property string $name
 * @property string $name_la
 *
 * @property \app\models\LocationBusines[] $locationBusines
 * @property string $aliasModel
 */
abstract class TypeLocation extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'type_location';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'name_la'], 'required'],
            [['name', 'name_la'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'name_la' => 'Name La',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocationBusines()
    {
        return $this->hasMany(\app\models\LocationBusines::className(), ['type_location_id' => 'id']);
    }




}
