<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "villages".
 *
 * @property integer $id
 * @property string $vill_code
 * @property string $vill_name
 * @property string $vill_name_la
 * @property double $latitute
 * @property double $longtitute
 * @property integer $districts_id
 * @property integer $provinces_id
 *
 * @property \app\models\LocationDetails[] $locationDetails
 * @property \app\models\Districts $districts
 * @property \app\models\Provinces $provinces
 * @property string $aliasModel
 */
abstract class Villages extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'villages';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['latitute', 'longtitute', 'districts_id', 'provinces_id'], 'required'],
            [['latitute', 'longtitute'], 'number'],
            [['districts_id', 'provinces_id'], 'integer'],
            [['vill_code', 'vill_name', 'vill_name_la'], 'string', 'max' => 255],
            [['districts_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Districts::className(), 'targetAttribute' => ['districts_id' => 'id']],
            [['provinces_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Provinces::className(), 'targetAttribute' => ['provinces_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'vill_code' => 'Vill Code',
            'vill_name' => 'Vill Name',
            'vill_name_la' => 'Vill Name La',
            'latitute' => 'Latitute',
            'longtitute' => 'Longtitute',
            'districts_id' => 'Districts ID',
            'provinces_id' => 'Provinces ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLocationDetails()
    {
        return $this->hasMany(\app\models\LocationDetails::className(), ['villages_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDistricts()
    {
        return $this->hasOne(\app\models\Districts::className(), ['id' => 'districts_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProvinces()
    {
        return $this->hasOne(\app\models\Provinces::className(), ['id' => 'provinces_id']);
    }




}
